<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>TuTa.Wms</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TuTa.Wms.Domain\TuTa.Wms.Domain.csproj" />
    <ProjectReference Include="..\TuTa.Wms.TestBase\TuTa.Wms.TestBase.csproj" />
  </ItemGroup>

</Project>
